const descriptions={compress:'Compress IMAGE',resize:'Resize IMAGE',crop:'Crop IMAGE',convert:'Convert image format',edit:'Photo editor',upscale:'Upscale IMAGE', 'remove-background':'Remove background',meme:'Meme generator',rotate:'Rotate IMAGE',watermark:'Watermark IMAGE',blur:'Blur area','html-to-image':'HTML to IMAGE'};
const detail={compress:'Reduce the size of your image while maintaining its format and quality.',resize:'Set the output dimensions in pixels. Images keep their proportions.',crop:'Enter the pixel coordinates and size of the area to keep.',convert:'Convert your image to another popular format.',edit:'Make a quick adjustment to color, contrast and sharpness.',upscale:'Enlarge your image using high quality resampling.', 'remove-background':'Remove a flat solid color background. For best results choose the background color.',meme:'Add top and bottom captions to your image.',rotate:'Choose an angle and rotate the image.',watermark:'Stamp your image with a text watermark.',blur:'Blur a rectangular area to obscure private details.','html-to-image':'Webpage capture needs a browser rendering engine that is not configured in this version.'};
const state={tool:'compress',file:null,fileUrl:null};
const $=s=>document.querySelector(s);
function revokeFileUrl(){if(state.fileUrl){URL.revokeObjectURL(state.fileUrl);state.fileUrl=null;}}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function field(label,name,value,type='number',wide=false,attrs=''){return `<div class="field${wide?' wide':''}"><label for="opt-${name}">${label}</label><input id="opt-${name}" name="${name}" type="${type}" value="${value}" ${attrs}></div>`}
function renderOptions(tool){switch(tool){case'resize':return field('Width (px)','width','1200')+field('Height (px)','height','0');case'crop':case'blur':return field('Left (px)','crop_x','0')+field('Top (px)','crop_y','0')+field(tool==='blur'?'Area width (px)':'Crop width (px)','crop_w','300')+field(tool==='blur'?'Area height (px)':'Crop height (px)','crop_h','300');case'compress':return field('Quality','quality','82','number',false,'min="10" max="95"');case'upscale':return `<div class="field wide"><label for="opt-width">Enlarge by</label><select id="opt-width" name="width"><option value="2">2×</option><option value="3">3×</option><option value="4">4×</option></select></div>`;case'rotate':return `<div class="field wide"><label for="opt-degrees">Rotation angle</label><select id="opt-degrees" name="degrees"><option value="90">90° clockwise</option><option value="180">180°</option><option value="270">270° clockwise</option></select></div>`;case'watermark':return field('Watermark text','text','ScottIMG','text',true);case'meme':return field('Top caption','text','TOP TEXT','text',true)+field('Bottom caption','bg_color','BOTTOM TEXT','text',true);case'convert':return `<div class="field wide"><label for="opt-bg_color">Output format</label><select name="bg_color" id="opt-bg_color"><option value="jpg">JPG</option><option value="png">PNG</option><option value="webp">WebP</option><option value="gif">GIF</option><option value="bmp">BMP</option></select></div>`;case'remove-background':return `<div class="field"><label for="opt-bg_color">Background color</label><input id="opt-bg_color" name="bg_color" type="color" value="#ffffff"></div>`;default:return `<div class="field wide"><label>Adjustment</label><p style="font-size:12px;color:#777;margin:0">Balanced color, contrast and sharpness enhancement.</p></div>`}}
function selectTool(tool){revokeFileUrl();state.tool=tool;state.file=null;$('#workspace').hidden=false;$('#work-title').textContent=descriptions[tool]||tool;$('#work-description').textContent=detail[tool];$('#options').innerHTML=renderOptions(tool);$('#file-input').value='';$('#file-input').accept=tool==='html-to-image'?'.html,.htm,text/html':'image/*';$('#file-list').innerHTML='';$('#run-tool').disabled=true;$('#status').textContent='';$('#status').className='status';$('#download').hidden=true;$('#workspace').scrollIntoView({behavior:'smooth',block:'start'});}
document.querySelectorAll('.tool-card, .quick-nav a[href^="#"]').forEach(card=>card.addEventListener('click',e=>{e.preventDefault();selectTool(card.getAttribute('href').slice(1));}));
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===button));let n=0;document.querySelectorAll('.tool-card').forEach(card=>{const show=button.dataset.filter==='all'||card.dataset.cat===button.dataset.filter;card.hidden=!show;if(show)n++;});$('.empty').hidden=n!==0;}));
$('#select-file').addEventListener('click',()=>$('#file-input').click());
$('#file-input').addEventListener('change',e=>setFile(e.target.files[0]));
function setFile(file){
  if(!file)return;
  revokeFileUrl();
  state.file=file;
  const info=`${escapeHtml(file.name)} · ${(file.size/1024/1024).toFixed(2)} MB`;
  let thumbHtml;
  if(file.type.startsWith('image/')){
    state.fileUrl=URL.createObjectURL(file);
    thumbHtml=`<span class="file-thumb"><img src="${state.fileUrl}" alt=""></span>`;
  } else {
    const ext=(file.name.split('.').pop()||'FILE').toUpperCase().slice(0,4);
    thumbHtml=`<span class="file-thumb"><span class="file-thumb-icon">${escapeHtml(ext)}</span></span>`;
  }
  $('#file-list').innerHTML=`${thumbHtml}<span class="file-name">${info}</span>`;
  $('#run-tool').disabled=false;$('#download').hidden=true;$('#status').textContent='Ready to process.';$('#status').className='status';
}
const drop=$('#drop-zone');drop.addEventListener('dragover',e=>{e.preventDefault();drop.classList.add('drag')});drop.addEventListener('dragleave',()=>drop.classList.remove('drag'));drop.addEventListener('drop',e=>{e.preventDefault();drop.classList.remove('drag');setFile(e.dataTransfer.files[0])});
$('.close-work').addEventListener('click',()=>{$('#workspace').hidden=true;$('#tools').scrollIntoView({behavior:'smooth'});});
$('#run-tool').addEventListener('click',async()=>{if(!state.file)return;const btn=$('#run-tool'),status=$('#status'),download=$('#download');btn.disabled=true;download.hidden=true;status.className='status';status.textContent='Working on your image…';try{const body=new FormData();body.append('file',state.file);$('#options').querySelectorAll('input,select').forEach(el=>body.append(el.name,el.value));const res=await fetch(`api/process/${state.tool}`,{method:'POST',body});if(!res.ok){let message=`Could not process this file (HTTP ${res.status}).`;try{message=(await res.json()).detail||message}catch{}throw new Error(message)}const blob=await res.blob();const url=URL.createObjectURL(blob);download.href=url;download.download=res.headers.get('content-disposition')?.match(/filename="?([^";]+)"?/)?.[1]||`scottimg-${state.tool}.png`;download.hidden=false;status.textContent='Done. Your image is ready to download.'}catch(e){status.textContent=e.message;status.classList.add('error')}finally{btn.disabled=!state.file}});
document.querySelectorAll('.tool-card[href]').forEach(()=>{});
if(location.hash&&descriptions[location.hash.slice(1)])selectTool(location.hash.slice(1));
